d = new dTree("d");
<!--
d.add("0","-1","Gradle资料","");
d.add("1","0","Gradle Goodness","");
d.add("2","1","Download Javadoc Files For Dependencies In IDE","my_data/Gradle_Goodness/Download_Javadoc_Files_For_Dependencies_In_IDE.htm");
d.add("3","1","Set Java Compiler Encoding","my_data/Gradle_Goodness/Set_Java_Compiler_Encoding.htm");
d.add("4","1","Use gradlew for Easy Gradle Execution","my_data/Gradle_Goodness/Use_gradlew_for_Easy_Gradle_Execution.htm");
d.add("5","1","Using Gradle for a Mixed Java and Groovy Project","my_data/Gradle_Goodness/Using_Gradle_for_a_Mixed_Java_and_Groovy_Project.htm");
d.add("6","1","Handle Copying Duplicate Files","my_data/Gradle_Goodness/Handle_Copying_Duplicate_Files.htm");
d.add("7","1","Renaming Files while Copying","my_data/Gradle_Goodness/Renaming_Files_while_Copying.htm");
d.add("8","1","Continue Build Even with Failed Tasks","my_data/Gradle_Goodness/Continue_Build_Even_with_Failed_Tasks.htm");
d.add("9","1","Check Task Dependencies With a Dry Run","my_data/Gradle_Goodness/Check_Task_Dependencies_With_a_Dry_Run.htm");
d.add("10","1","Show Standard Out or Error Output from Tests","my_data/Gradle_Goodness/Show_Standard_Out_or_Error_Output_from_Tests.htm");
d.add("11","1","Run Java Application From Build Script","my_data/Gradle_Goodness/Run_Java_Application_From_Build_Script.htm");
d.add("12","1","Running Groovy Scripts as Application","my_data/Gradle_Goodness/Running_Groovy_Scripts_as_Application.htm");
d.add("13","1","Getting More Dependency Insight","my_data/Gradle_Goodness/Getting_More_Dependency_Insight.htm");
d.add("14","1","Unpacking an Archive","my_data/Gradle_Goodness/Unpacking_an_Archive.htm");
d.add("15","1","Get User Input Values From Console","my_data/Gradle_Goodness/Get_User_Input_Values_From_Console.htm");
d.add("16","1","Using Optional Ant Task in Gradle","my_data/Gradle_Goodness/Using_Optional_Ant_Task_in_Gradle.htm");
d.add("17","0","Web","");
d.add("18","17","创建Web应用项目","my_data/web/创建Web应用项目/index.html");
d.add("19","17","使用Gradle构建Java Web应用","my_data/web/(WJW)使用Gradle构建Java Web应用.htm");
d.add("20","17","Eclipse中进行Gradle+Jetty部署的web项目的断点调试","my_data/web/Eclipse中进行Gradle+Jetty部署的web项目的断点调试/index.html");
d.add("21","17","Gradle构建Java Web应用：Servlet依赖与Tomcat插件","my_data/web/Gradle构建Java_Web应用：Servlet依赖与Tomcat插件.htm");
d.add("22","17","Gradle添加tomcat插件","my_data/web/为Gradle添加tomcat插件/index.html");
d.add("23","17","Gradle Tomcat plugin","my_data/web/Gradle_Tomcat_plugin.htm");
d.add("24","0","Gradle用户手册","");
d.add("25","24","1. 简介 - Introduction(已完成)","my_data/Gradle用户手册/1. 简介 - Introduction/1._简介_-_Introduction(已完成).htm");
d.add("26","25","1.1. 关于本手册 - About this user guide","my_data/Gradle用户手册/1. 简介 - Introduction/1._简介_-_Introduction(已完成).htm");
d.add("27","24","2. 概述 - Overview","my_data/Gradle用户手册/2. 概述 - Overview/2._概述_-_Overview.htm");
d.add("28","27","2.1. Features","");
d.add("29","27","2.2. Why Groovy?","");
d.add("30","24","3.教程说明 - Tutorials(已完成)","");
d.add("31","30","3.1. 快速开始 - Getting Started","");
d.add("32","24","4. 安装 - Installing Gradle(已完成)","");
d.add("33","32","4.1. 先决条件 - Prerequisites","");
d.add("34","32","4.2. 下载 - Download","");
d.add("35","32","4.3. 解压 - Unpacking","");
d.add("36","32","4.4. 环境变量配置 - Environment variables","");
d.add("37","32","4.5. 安装测试 - Running and testing your installation","");
d.add("38","32","4.6. JVM参数配置 - JVM options","");
d.add("39","0","Gradle一般使用常见问答","my_data/Gradle一般使用常见问答.htm");
d.add("40","0","Gradle中的buildScript代码块","my_data/Gradle中的buildScript代码块/index.html");
d.add("41","0","(WJW)Gradle使用maven本地仓库","my_data/(WJW)Gradle使用maven本地仓库.htm");
d.add("42","0","Gradle修改Maven仓库地址","my_data/Gradle修改Maven仓库地址.htm");
d.add("43","0","Gradle打包Groovy脚本成 jar与上传到maven repository","my_data/Gradle打包Groovy脚本成_jar与上传到maven_repository.htm");
d.add("44","0","Gradle_脚本中处理Manifest__ClassPath","my_data/Gradle_脚本中处理Manifest__ClassPath.htm");
d.add("45","0","Gradle build without tests","my_data/Gradle build without tests.htm");
d.add("46","0","Gradle File dependencies","my_data/Gradle_File_dependencies.htm");
d.add("47","0","Gradle 构建工具 介绍","my_data/Gradle_构建工具_介绍.htm");
d.add("48","0","在 Eclipse 下利用 gradle 构建系统","my_data/在 Eclipse 下利用 gradle 构建系统.htm");
d.add("49","0","(wjw)Gradle秘籍","my_data/(wjw)Gradle秘籍.md.html");
d.add("50","0","(WJW)Maven项目秒变gradle项目","my_data/(WJW)Maven项目秒变gradle项目.htm");
d.add("51","0","快速创建java项目框架","my_data/快速创建java项目框架.htm");
d.add("52","0","解决Gradle编译时出现： 编码GBK的不可映射字符","my_data/解决Gradle编译时出现：_编码GBK的不可映射字符.htm");
d.add("53","0","Gradle的依赖管理(Repository&Dependency )","my_data/Gradle的依赖管理(Repository&Dependency_).htm");
d.add("54","0","Standard project properties","my_data/Standard_project_properties.htm");
d.add("55","0","使用Gradle 插件进行代码分析","my_data/使用Gradle插件进行代码分析/index.html");
document.write(d);
//-->
