d = new dTree("d");
<!--
d.add("0","-1","Groovy指南","");
d.add("1","0","注意CodeCache的设置","my_data/注意CodeCache的设置.htm");
d.add("2","0","使用Groovy需要注意的几个点","my_data/使用Groovy需要注意的几个点.htm");
d.add("3","0","嵌入Groovy大全(java中调用groovy)","my_data/嵌入Groovy.htm");
d.add("4","0","Java中使用Groovy实现自定义表达式解析","my_data/Java中使用Groovy实现自定义表达式解析.htm");
d.add("5","0","获取Spring的WebApplicationContext","my_data/获取Spring的WebApplicationContext.htm");
d.add("6","0","Groovy操纵集合秘籍","my_data/Groovy操纵集合秘籍.html");
d.add("7","0","实战 Groovy: 美妙的操作符","my_data/实战_Groovy__美妙的操作符.htm");
d.add("8","0","便捷，轻巧的Groovy数据库操作","my_data/便捷，轻巧的Groovy数据库操作.htm");
d.add("9","0","Groovy在Spring中的简单使用","my_data/Groovy在Spring中的简单使用.htm");
d.add("10","0","Gradle 打包 Groovy 脚本成 jar与上传到maven repository","my_data/Gradle打包Groovy脚本成 jar与上传到maven repository.htm");
d.add("11","0","The MarkupTemplateEngine","my_data/markup-template-engine.html");
d.add("12","0","官方例子","");
d.add("13","12","Groovy - Calculating a SHA1 hash for large files","my_data/官方例子/Groovy - Calculating a SHA1 hash for large files.htm");
d.add("14","12","Groovy - ConfigSlurper","my_data/官方例子/Groovy - ConfigSlurper.htm");
d.add("15","12","Groovy - Convert SQL Result To XML","my_data/官方例子/Groovy - Convert SQL Result To XML.htm");
d.add("16","12","Groovy - Creating Larger XML using StreamingMarkupBuilder","my_data/官方例子/Groovy - Creating Larger XML using StreamingMarkupBuilder.htm");
d.add("17","12","Groovy - Creating XML using Groovy's MarkupBuilder","my_data/官方例子/Groovy - Creating XML using Groovy's MarkupBuilder.htm");
d.add("18","12","Groovy - GPath","my_data/官方例子/Groovy - GPath.htm");
d.add("19","12","Groovy - Groovy Templates","my_data/官方例子/Groovy - Groovy Templates.htm");
d.add("20","12","Groovy - Reading XML using Groovy's XmlSlurper","my_data/官方例子/Groovy - Reading XML using Groovy's XmlSlurper.htm");
d.add("21","12","Groovy - Updating XML with XmlSlurper","my_data/官方例子/Groovy - Updating XML with XmlSlurper.htm");
d.add("22","12","Groovy - Validating XML with a W3C XML Schema","my_data/官方例子/Groovy - Validating XML with a W3C XML Schema.htm");
d.add("23","12","Working with JMX","my_data/官方例子/The Groovy programming language - Working with JMX.htm");
d.add("24","0","秘诀","");
d.add("25","24","Map Shortcuts","my_data/秘诀/Map_Shortcuts.htm");
d.add("26","24","Optional Parameters/Default Values","my_data/秘诀/Optional_Parameters_Default_Values.htm");
d.add("27","24","Using Shell Wildcards in Groovy Scripts","my_data/秘诀/Using_Shell_Wildcards_in_Groovy_Scripts.htm");
d.add("28","24","Waiting for a Shell Command to Finish Before Continuing","my_data/秘诀/Waiting_for_a_Shell_Command_to_Finish_Before_Continuing.htm");
d.add("29","24","Calling Another Groovy Script","my_data/秘诀/Calling_Another_Groovy_Script.htm");
d.add("30","24","Listing All Files in a Directory","my_data/秘诀/Listing_All_Files_in_a_Directory.htm");
d.add("31","24","Copying Files","my_data/秘诀/Copying_Files.htm");
d.add("32","24","Using AntBuilder to Copy a File","my_data/秘诀/Using_AntBuilder_to_Copy_a_File.htm");
d.add("33","24","Creating a ZIP File/Tarball","my_data/秘诀/Creating_a_ZIP_File_Tarball.htm");
d.add("34","24","Unzipping/Untarring Files","my_data/秘诀/Unzipping_Untarring_Files.htm");
d.add("35","24","Dealing with XML Attributes","my_data/秘诀/Dealing_with_XML_Attributes.htm");
d.add("36","24","Navigating Deeply Nested XML","my_data/秘诀/Navigating_Deeply_Nested_XML.htm");
d.add("37","24","Parsing an XML Document with Namespaces","my_data/秘诀/Parsing_an_XML_Document_with_Namespaces.htm");
d.add("38","24","Creating Namespaced XML Using MarkupBuilder","my_data/秘诀/Creating_Namespaced_XML_Using_MarkupBuilder.htm");
d.add("39","24","Understanding the Difference Between MarkupBuilder and StreamingMarkupBuilder","my_data/秘诀/Understanding_the_Difference_Between_MarkupBuilder_and_StreamingMarkupBuilder.htm");
d.add("40","24","Creating Parts of the XML Document Separately","my_data/秘诀/_Creating_Parts_of_the_XML_Document_Separately.htm");
d.add("41","24","Creating HTML on the Fly","my_data/秘诀/Creating_HTML_on_the_Fly.htm");
d.add("42","24","Making an HTTP GET Request","my_data/秘诀/Making_an_HTTP_GET_Request.htm");
d.add("43","24","Making an HTTP POST Request","my_data/秘诀/Making_an_HTTP_POST_Request.htm");
d.add("44","24","Discovering the Class","my_data/秘诀/Discovering_the_Class.htm");
d.add("45","24","Discovering the Fields of a Class","my_data/秘诀/Discovering_the_Fields_of_a_Class.htm");
d.add("46","24","Checking for the Existence of a Field","my_data/秘诀/Checking_for_the_Existence_of_a_Field.htm");
d.add("47","24","Discovering the Methods of a Class","my_data/秘诀/Discovering_the_Methods_of_a_Class.htm");
d.add("48","24","Checking for the Existence of a Method","my_data/秘诀/Checking_for_the_Existence_of_a_Method.htm");
d.add("49","24","Calling Methods That Don't Exist (invokeMethod)","my_data/秘诀/Calling_Methods_That_Don't_Exist_(invokeMethod).htm");
d.add("50","24","Adding Methods to a Class Dynamically (Categories)","my_data/秘诀/Adding_Methods_to_a_Class_Dynamically_(Categories).htm");
d.add("51","24","Adding Methods to a Class Dynamically (ExpandoMetaClass)","my_data/秘诀/Adding_Methods_to_a_Class_Dynamically_(ExpandoMetaClass).htm");
d.add("52","0","Json","");
d.add("53","52","Groovy 1.8 新特性: 原生 JSON 支持","my_data/Json/Groovy_1.8_新特性__原生_JSON_支持.htm");
d.add("54","52","groovy 操作json实例","my_data/Json/groovy 操作json实例.htm");
d.add("55","52","groovy JsonBuilder将对象转向json","my_data/Json/groovy_JsonBuilder将对象转向json.htm");
d.add("56","52","Writing json output from a groovlet | Stuff I've learned recently...","my_data/Json/Writing json output from a groovlet.htm");
d.add("57","0","Servlet","");
d.add("58","57","获取Spring的WebApplicationContext","my_data/获取Spring的WebApplicationContext.htm");
d.add("59","57","groovy:groovyservlet 乱码问题,解决","my_data/groovy-groovyservlet 乱码问题,解决.htm");
d.add("60","57","Groovy笔记(12)_Groovlet","my_data/Groovy笔记(12)_Groovlet.htm");
d.add("61","57","用groovyServlet和TemplateServlet快速开发网页","my_data/用GroovyServlet和TemplateServlet快速开发网页.htm");
d.add("62","57","用 Groovlet 和 GSP 进行动态服务器端编程","my_data/用_Groovy_打造服务器端.htm");
d.add("63","57","groovy及其TemplateServlet的编码问题","my_data/Groovy及其TemplateServlet的编码问题.htm");
d.add("64","0","Sql","");
d.add("65","64","Groovy Sql 知识点整理","my_data/Sql/Groovy_Sql_知识点整理.md.html");
d.add("66","64","Notes about Groovy's DataSet","my_data/Sql/Notes_about_Groovy's_DataSet.htm");
d.add("67","64","Use Sql under transaction","my_data/Sql/Test_Sql_transaction_features_using_a_Sql_built_from_a_connection.htm");
d.add("68","64","Batch Sql","my_data/Sql/Batch_Sql.htm");
d.add("69","0","Groovy 2.0新特性","my_data/Groovy 2.0新特性.htm");
d.add("70","0","Groovy的脚本引擎-GroovyScriptEngine","my_data/Groovy的脚本引擎-GroovyScriptEngine_.htm");
d.add("71","0","JAVA嵌入运行Groovy脚本","my_data/JAVA嵌入运行Groovy脚本.htm");
d.add("72","0","java 中调用 groovy","my_data/java中调用groovy.htm");
d.add("73","0","Groovy Goodness: New Dollar Slashy Strings - Messages from mrhaki","my_data/(新的字符串定义符)New Dollar Slashy Strings.htm");
d.add("74","0","Groovy 与 DSL","my_data/Groovy与DSL.htm");
d.add("75","0","groovy的DSL(2)","my_data/Groovy的DSL(2).htm");
d.add("76","0","Groovy解惑-Closure中的delegate","my_data/Groovy解惑-Closure中的delegate.htm");
d.add("77","0","Groovy解惑-Closure中的owner,this,delegate","my_data/Groovy解惑-Closure中的owner,this,delegate.htm");
d.add("78","0","java程序员为什么使用Groovy","my_data/java程序员为什么使用Groovy.htm");
d.add("79","0","打动你朋友的11条Groovy超炫代码","my_data/打动你朋友的11条Groovy超炫代码.htm");
d.add("80","0","即时编译和打包您的 Groovy 脚本","my_data/即时编译和打包您的 Groovy 脚本/index.html");
d.add("81","0","嵌入Groovy脚本时添加一些默认import","my_data/嵌入Groovy脚本时添加一些默认import.htm");
d.add("82","0","如何判断文件是文本还是二进制","my_data/如何判断文件是文本还是二进制.htm");
d.add("83","0","Groovy 1.8 新特性: 增强的 AST","my_data/Groovy_1.8_新特性__增强的_AST.htm");
d.add("84","0","闭包作为注释的参数","my_data/闭包作为注释的参数.htm");
d.add("85","0","使用 Groovy 获取classpath中的资源","my_data/使用_Groovy_获取代码树中的资源.htm");
d.add("86","0","在 Gradle 脚本中处理Manifest: ClassPath","my_data/Gradle_脚本中处理Manifest__ClassPath.htm");
d.add("87","0","Customizing Groovy compilation process(阻止System.exit())","my_data/Customizing Groovy compilation process(阻止System.exit()).htm");
d.add("88","0","Groovy: 比JavaBean好用的GroovyBean - zjumty - ITeye技术网站","my_data/Groovy- 比JavaBean好用的GroovyBean.htm");
d.add("89","0","实战 Groovy: 构建和解析 XML","my_data/实战_Groovy__构建和解析_XML.htm");
d.add("90","0","Groovy用inject方法构造Map","my_data/Groovy用inject方法构造Map.htm");
d.add("91","0","List对象的transpose和inject方法的使用","my_data/List对象的transpose和inject方法的使用.htm");
d.add("92","0","Groovy闭包详解","my_data/Groovy闭包详解.htm");
d.add("93","0","实战 Groovy: for each 剖析","my_data/实战_Groovy__for_each_剖析.htm");
d.add("94","0","用Groovy模板写MyBatis动态SQL","my_data/用Groovy模板写MyBatis动态SQL.htm");
document.write(d);
//-->
